import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/sale.dart';
import '../models/app_settings.dart';
import 'settings_service.dart';

class ReceiptService {
final SettingsService _settingsService =
SettingsService();

//=========================================
// Generate Receipt
//=========================================

Future<File> generateReceipt(
Sale sale,
) async {

final pdf = pw.Document();

final AppSettings settings =
await _settingsService.getSettings();

final String formattedDate =
DateFormat(
"dd/MM/yyyy HH:mm",
).format(
DateTime.parse(sale.saleDate),
);
pdf.addPage(
pw.Page(
pageFormat: PdfPageFormat.a4,

build: (context) {
return pw.Column(
crossAxisAlignment:
pw.CrossAxisAlignment.start,

children: [

//==================================
// SHOP HEADER
//==================================

pw.Center(
child: pw.Text(
settings.shopName,
style: pw.TextStyle(
fontSize: 24,
fontWeight:
pw.FontWeight.bold,
),
),
),

pw.SizedBox(height: 6),

pw.Center(
child: pw.Text(
"Owner: ${settings.ownerName}",
),
),

pw.Center(
child: pw.Text(
"Phone: ${settings.phone}",
),
),

pw.Center(
child: pw.Text(
settings.address,
textAlign:
pw.TextAlign.center,
),
),

pw.Divider(),

//==================================
// RECEIPT DETAILS
//==================================

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,

children: [

pw.Text(
"Receipt No:",
style: pw.TextStyle(
fontWeight:
pw.FontWeight.bold,
),
),

pw.Text(
"#${sale.id}",
),
],
),

pw.SizedBox(height: 5),

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,

children: [

pw.Text(
"Date:",
style: pw.TextStyle(
fontWeight:
pw.FontWeight.bold,
),
),

pw.Text(
formattedDate,
),
],
),

pw.Divider(),

//==================================
// PRODUCT DETAILS
//==================================

pw.Text(
"PRODUCT INFORMATION",
style: pw.TextStyle(
fontWeight:
pw.FontWeight.bold,
fontSize: 16,
),
),

pw.SizedBox(height: 10),

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,
children: [
pw.Text("Product"),
pw.Text(sale.productName),
],
),

pw.SizedBox(height: 6),

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,
children: [
pw.Text("Category"),
pw.Text(sale.category),
],
),

pw.SizedBox(height: 6),

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,
children: [
pw.Text("Quantity"),
pw.Text(
sale.quantity.toString(),
),
],
),

pw.SizedBox(height: 6),

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,
children: [
pw.Text("Unit Price"),
pw.Text(
sale.sellingPrice
.toStringAsFixed(2),
),
],
),

pw.Divider(),

//==================================
// TOTALS
//==================================

pw.Row(
mainAxisAlignment:
pw.MainAxisAlignment
.spaceBetween,
children: [

pw.Text(
"Total",
style: pw.TextStyle(
fontWeight:
pw.FontWeight.bold,
),
),

pw.Text(
sale.totalSelling
.toStringAsFixed(2),
style: pw.TextStyle(
fontWeight:
pw.FontWeight.bold,
),
),
],
),
  pw.Divider(),

  pw.SizedBox(height: 10),

  pw.Center(
    child: pw.Text(
      "Thank you for your purchase!",
      style: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        fontSize: 16,
      ),
    ),
  ),

  //==================================
  // RECEIPT FOOTER
  //==================================

  pw.SizedBox(height: 20),

  pw.Center(
    child: pw.Text(
      settings.receiptFooter,
      textAlign: pw.TextAlign.center,
      style: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        fontSize: 14,
      ),
    ),
  ),

  pw.SizedBox(height: 10),

  pw.Center(
    child: pw.Text(
      "Generated by Shop Management System",
      style: const pw.TextStyle(
        fontSize: 10,
      ),
    ),
  ),
],
);
},
),
);

//=========================================
// SAVE PDF
//=========================================

final Directory directory =
await getApplicationDocumentsDirectory();

final String filePath =
    "${directory.path}/receipt_${sale.id}.pdf";

final File file = File(filePath);

await file.writeAsBytes(
  await pdf.save(),
);

return file;
}

  //=========================================
  // OPEN RECEIPT
  //=========================================

  Future<void> openReceipt(
      Sale sale,
      ) async {
    final pdf = await generateReceipt(sale);

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async {
        return pdf.readAsBytes();
      },
    );
  }

  //=========================================
  // PRINT RECEIPT
  //=========================================

  Future<void> printReceipt(
      Sale sale,
      ) async {
    final pdf = await generateReceipt(sale);

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async {
        return pdf.readAsBytes();
      },
    );
  }
}